export const songs = [
  {
    backgroundColor: "#f196b0",
    textColor: "#000",
    url: require("../music/1-second-of-silence.mp3"),
    title: "",
    backgroundImage: require("../image/music1.jpg"),
    subTextImage: require("../image/album-text-white.png"),
  },
  {
    backgroundColor: "#f196b0",
    textColor: "#000",
    url: require("../music/we-dont-talk-anymore.mp3"),
    title: "We don't talk anymore",
    author: "Charlie Puth",
    backgroundImage: require("../image/music1.jpg"),
    subTextImage: require("../image/album-text-white.png"),
  },
  {
    backgroundColor: "#95d1f2",
    textColor: "#1c2a39",
    url: require("../music/sparkle.mp3"),
    title: "Sparkle - Your name. movie ver",
    author: "RADWIMPS",
    backgroundImage: require("../image/sparkle-yourname1.png"),
    subTextImage: require("../image/album-text-white.png"),
  },
  {
    backgroundColor: "#fff",
    textColor: "#ff8244",
    url: require("../music/luoiii.mp3"),
    title: "Lườiii",
    author: "Low G, Ska, tlinh",
    backgroundImage: require("../image/lowg.png"),
    subTextImage: require("../image/album-text-white.png"),
  },
  {
    backgroundColor: "#77817d",
    textColor: "#35383d",
    url: require("../music/dung_goi_anh_day.mp3"),
    title: "Đừng gọi anh dậy",
    author: "Phúc Du",
    backgroundImage: require("../image/dung_goi_anh_day.png"),
    subTextImage: require("../image/album-text-white.png"),
  },
  {
    backgroundColor: "#ff8244",
    textColor: "#3c3c3c",
    url: require("../music/khong_thich.mp3"),
    title: "Không thích",
    author: "Low G",
    backgroundImage: require("../image/lowg.png"),
    subTextImage: require("../image/album-text-white.png"),
  },
];
