export const songs = [
	{
		backgroundColor: "#e5d0c3",
		textColor: "#6a3474",
		url: require("../music/X2Download.app - eaJ x Seori - It just is (Feat. Keshi's Strat) (128 kbps).mp3"),
		title: "eaJ x Seori - It just is (Feat. Keshi's Strat)",
		author: "eaJ x Seori ft. Keshi",
		backgroundImage: require("../image/keshi1.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#f196b0",
		textColor: "#000",
		url: require("../music/we-dont-talk-anymore.mp3"),
		title: "We don't talk anymore",
		author: "Charlie Puth",
		backgroundImage: require("../image/music1.jpg"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#95d1f2",
		textColor: "#1c2a39",
		url: require("../music/sparkle.mp3"),
		title: "Sparkle - Your name. movie ver",
		author: "RADWIMPS",
		backgroundImage: require("../image/sparkle-yourname1.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#fff",
		textColor: "#ff8244",
		url: require("../music/luoiii.mp3"),
		title: "Lườiii",
		author: "Low G, Ska, tlinh",
		backgroundImage: require("../image/lowg.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#77817d",
		textColor: "#35383d",
		url: require("../music/dung_goi_anh_day.mp3"),
		title: "Đừng gọi anh dậy",
		author: "Phúc Du",
		backgroundImage: require("../image/dung_goi_anh_day.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#ff8244",
		textColor: "#111111",
		url: require("../music/khong_thich.mp3"),
		title: "Không thích",
		author: "Low G",
		backgroundImage: require("../image/lowg.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#ffb436",
		textColor: "#b84117",
		url: require("../music/nuoc-mat-em-lau-bang-tinh-yeu-moi.mp3"),
		title: "Nước mắt em lau bằng tình yêu mới",
		author: "Dalab ft. Tóc Tiên",
		backgroundImage: require("../image/nuocmatemlaubangtinhyeumoi.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#9cb7dc",
		textColor: "#1a1d29",
		url: require("../music/em-bo-hut-thuoc-chua.mp3"),
		title:
			"em bỏ hút thuốc chưa - người yêu cũ nhắn tin hỏi nhưng bích phương không muốn trả lời",
		author: "Bích Phương",
		backgroundImage: require("../image/em-bo-hut-thuoc-chua.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#fe3fb9",
		textColor: "#290748",
		url: require("../music/phong-cach.mp3"),
		title: "phong cách",
		author: "MCK",
		backgroundImage: require("../image/phong cach.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#beb4a4",
		textColor: "#1d2863",
		url: require("../music/X2Download.app - GREY D x tlinh - vaicaunoicokhiennguoithaydoi _ Official Music Video (128 kbps).mp3"),
		title: "vaicaunoicokhiennguoithaydoi",
		author: "GREY D x tlinh",
		backgroundImage: require("../image/vaicaunoicokhiennguoithaydoi.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#af3236",
		textColor: "#0b2229",
		url: require("../music/showmelove.mp3"),
		title: "Show Me Love",
		author: "MCK",
		backgroundImage: require("../image/showmelove.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#9e3d13",
		textColor: "#d4bc50",
		url: require("../music/X2Download.app - Lyric Video _ đứa nào làm em buồn_ - Phúc Du ft. Hoàng Dũng (128 kbps).mp3"),
		title: "đứa nào làm em buồn",
		author: "Phúc Du ft. Hoàng Dũng",
		backgroundImage: require("../image/duanaolamembuon.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#e5b0a5",
		textColor: "#32532f",
		url: require("../music/X2Download.app - [Vietsub] Johnny Stimson _ Flower (128 kbps).mp3"),
		title: "Flower",
		author: "Johnny Stimson",
		backgroundImage: require("../image/flower.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#275f7b",
		textColor: "#16211a",
		url: require("../music/X2Download.app - keshi - skeletons (Audio) (320 kbps).mp3"),
		title: "skeletons",
		author: "keshi",
		backgroundImage: require("../image/keshi.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
	{
		backgroundColor: "#cf2935",
		textColor: "#252121",
		url: require("../music/badtrip.mp3"),
		title: "Bad trip",
		author: "MCK",
		backgroundImage: require("../image/badtrip.png"),
		subTextImage: require("../image/album-text-white.png"),
	},
];
